export const allSoundEffects = [
  { name: 'one', src: './assets/sound/mixkit-arcade-mechanical-bling-210.wav' },
  { name: 'levelUp', src: './assets/sound/mixkit-game-bonus-reached-2065.wav' },
  { name: 'tetriminoMove', src: './assets/sound/mixkit-player-jumping-in-a-video-game-2043.wav' },
  { name: 'four', src: './assets/sound/mixkit-quick-positive-video-game-notification-interface-265.wav' },
  { name: 'five', src: './assets/sound/mixkit-sci-fi-positive-notification-266.wav' },
  { name: 'lineClear', src: './assets/sound/mixkit-video-game-health-recharge-2837.wav' },
  { name: 'eight', src: './assets/sound/mixkit-winning-a-coin-video-game-2069.wav' },
  { name: 'tetriminoLand', src: './assets/sound/mixkit-short-bass-hit-2299.wav' },
  { name: 'singleLineClear', src: null },
  { name: 'doubleLineClear', src: null },
  { name: 'tripleLineClear', src: null },
  { name: 'tetrisLineClear', src: null },
  { name: 'tSpin', src: null },
  { name: 'back2Back', src: null },
  { name: 'softdrop', src: null },
  { name: 'harddrop', src: null },
  { name: 'hold', src: null },
  { name: 'movementFailure', src: null },
  { name: 'rotationFailure', src: null },

  // Menu Sounds
  { name: 'menuBasicButtonClick', src: './assets/sound/menu-basic-button-click.wav' },
  { name: 'menuBasicButtonHover', src: './assets/sound/menu-basic-button-hover.wav' },
  { name: 'menuBackButtonClick', src: './assets/sound/menu-back-button.ogg' },
  { name: 'menuPlayerSlotRemove', src: './assets/sound/menu-playerslot-remove.mp3' },
  { name: 'menuPlayerSlotPlace', src: './assets/sound/menu-playerslot-place.wav' },
  { name: 'menuEnqueue', src: './assets/sound/menu-enqueue.wav' },
  { name: 'menuDequeue', src: './assets/sound/menu-dequeue.wav' },
  { name: 'matchFound', src: './assets/sound/menu-matchfound.wav' },
]